export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const DRAWER_SCREEN = 'DRAWER_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
